[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Next.js SSR Cache-Header
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
# Cache-Header für statische Assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Weiterleitung für client-seitiges Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Sicherheitsheader für alle Routen
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://www.google-analytics.com;
      frame-ancestors 'none';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Geschützte Pfade (wenn benötigt)
# [[redirects]]
#   from = "/admin/*"
#   to = "/admin/index.html"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}
#   conditions = {Role = "admin"}

# Fehlerseiten
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Komprimierung
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
